services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: another-knowlege-base
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    command:
      [
        'sh',
        '-c',
        'sleep 5 && node ./init-scripts/init-db.js && node ./dist/src/index.js',
      ]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
